export const ROLES = {
  OWNER: 'owner',
  BRANCH_MANAGER: 'branch_manager',
  CASHIER: 'cashier',
  SALES: 'sales',
  INVENTORY: 'inventory',
  PURCHASING: 'purchasing',
  ACCOUNTANT: 'accountant',
  VIEWER: 'viewer',
} as const;

export const PERMISSIONS = {
  // POS
  POS_SALE: 'pos:sale',
  POS_CANCEL: 'pos:cancel',
  POS_REPRINT: 'pos:reprint',
  POS_HOLD: 'pos:hold',

  // Products / Catalog
  PRODUCT_READ: 'products:read',
  PRODUCT_CREATE: 'products:create',
  PRODUCT_UPDATE: 'products:update',
  PRODUCT_DELETE: 'products:delete',

  // Categories
  CATEGORY_READ: 'categories:read',
  CATEGORY_CREATE: 'categories:create',
  CATEGORY_UPDATE: 'categories:update',
  CATEGORY_DELETE: 'categories:delete',

  // Customers
  CUSTOMER_READ: 'customers:read',
  CUSTOMER_CREATE: 'customers:create',
  CUSTOMER_UPDATE: 'customers:update',
  CUSTOMER_DELETE: 'customers:delete',
  CUSTOMER_PAYMENT: 'customers:payment',

  // Suppliers / Purchases
  SUPPLIER_READ: 'suppliers:read',
  SUPPLIER_CREATE: 'suppliers:create',
  SUPPLIER_UPDATE: 'suppliers:update',
  SUPPLIER_DELETE: 'suppliers:delete',
  SUPPLIER_INVOICE_CREATE: 'supplier_invoices:create',
  SUPPLIER_INVOICE_UPDATE: 'supplier_invoices:update',
  SUPPLIER_PAYMENT: 'suppliers:payment',

  // Expenses
  EXPENSE_READ: 'expenses:read',
  EXPENSE_CREATE: 'expenses:create',
  EXPENSE_UPDATE: 'expenses:update',
  EXPENSE_DELETE: 'expenses:delete',

  // Reports
  REPORT_READ: 'reports:read',

  // Users
  USER_READ: 'users:read',
  USER_CREATE: 'users:create',
  USER_UPDATE: 'users:update',
  USER_DELETE: 'users:delete',

  // Refunds
  REFUND_CREATE: 'refunds:create',

  // Inventory
  INVENTORY_READ: 'inventory:read',
  INVENTORY_ADJUST: 'inventory:adjust',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.POS_SALE,
    PERMISSIONS.POS_CANCEL,
    PERMISSIONS.POS_REPRINT,
    PERMISSIONS.POS_HOLD,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_PAYMENT,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_UPDATE,
    PERMISSIONS.SUPPLIER_INVOICE_CREATE,
    PERMISSIONS.SUPPLIER_PAYMENT,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.REFUND_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.POS_SALE,
    PERMISSIONS.POS_HOLD,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_PAYMENT,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_CREATE,
  ],
  [ROLES.SALES]: [
    PERMISSIONS.POS_SALE,
    PERMISSIONS.POS_HOLD,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_PAYMENT,
    PERMISSIONS.REPORT_READ,
  ],
  [ROLES.INVENTORY]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_INVOICE_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
  ],
  [ROLES.PURCHASING]: [
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_UPDATE,
    PERMISSIONS.SUPPLIER_INVOICE_CREATE,
    PERMISSIONS.SUPPLIER_INVOICE_UPDATE,
    PERMISSIONS.SUPPLIER_PAYMENT,
    PERMISSIONS.PRODUCT_READ,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_PAYMENT,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_PAYMENT,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.EXPENSE_READ,
  ],
};
